name: releaseWithOlivOS
on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
      - '*.*.*-*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OlivOSTag: ""
    steps:
      - name: Get OlivOS Latest Release Version Tag
        id: OlivOSTag
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'OlivOS-Team',
              repo: 'OlivOS',
            });
            const tagName = response.data.tag_name;
            console.log(`OlivOS Latest Release Version: ${tagName}`);
            core.exportVariable('OlivOSTag', tagName);
            return tagName;
      - uses: actions/checkout@v3
      - name: Download & Unpack OlivOS
        run: |
          mkdir ./download
          mkdir ./unpack
          mkdir ./release
          mkdir ./release-final
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Win.zip -o ./download/OlivOS-Win.zip
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Linux.zip -o ./download/OlivOS-Linux.zip
          echo "Download OlivOS Done"
          curl -L https://github.com/OlivOS-Team/ChanceCustom/releases/latest/download/ChanceCustom.opk -o ./download/ChanceCustom.opk
          cp ./download/ChanceCustom.opk ./unpack
          echo "Download ChanceCustom Done"
          mkdir ./unpack/OlivOS
          mkdir ./unpack/OlivOS-Linux
          unzip ./download/OlivOS-Win.zip -d ./unpack/OlivOS
          unzip ./download/OlivOS-Linux.zip -d ./unpack/OlivOS-Linux
          cp -r ./unpack/OlivOS ./release/OlivOS
          cp -r ./unpack/OlivOS-Linux ./release/OlivOS-Linux
          mkdir ./release/OlivOS/plugin
          mkdir ./release/OlivOS/plugin/app
          mkdir ./release/OlivOS-Linux/plugin
          mkdir ./release/OlivOS-Linux/plugin/app
          echo "Unpack OlivOS Done"
      - name: Checkout OlivaDiceCore
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceCore
          path: ./download/OlivaDiceCore/
      - name: Checkout OlivaDiceJoy
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceJoy
          path: ./download/OlivaDiceJoy/
      - name: Checkout OlivaDiceLogger
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceLogger
          path: ./download/OlivaDiceLogger/
      - name: Checkout OlivaDiceMaster
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceMaster
          path: ./download/OlivaDiceMaster/
      - name: Checkout OlivaDiceOdyssey
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceOdyssey
          path: ./download/OlivaDiceOdyssey/
      - name: Checkout OlivaStoryCore
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaStoryCore
          path: ./download/OlivaStoryCore/
      - name: Checkout OlivaDiceNativeGUI
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceNativeGUI
          path: ./download/OlivaDiceNativeGUI/
      - name: Pack & Setup OlivaDice
        run: |
          cd ./download/
          cd ./OlivaDiceCore/OlivaDiceCore
          zip -r ../../../unpack/OlivaDiceCore.opk ./
          cd ../../
          echo "Pack OlivaDiceCore Done"
          cd ./OlivaDiceJoy/OlivaDiceJoy
          zip -r ../../../unpack/OlivaDiceJoy.opk ./
          cd ../../
          echo "Pack OlivaDiceJoy Done"
          cd ./OlivaDiceLogger/OlivaDiceLogger
          zip -r ../../../unpack/OlivaDiceLogger.opk ./
          cd ../../
          echo "Pack OlivaDiceLogger Done"
          cd ./OlivaDiceMaster/OlivaDiceMaster
          zip -r ../../../unpack/OlivaDiceMaster.opk ./
          cd ../../
          echo "Pack OlivaDiceMaster Done"
          cd ./OlivaDiceOdyssey/OlivaDiceOdyssey
          zip -r ../../../unpack/OlivaDiceOdyssey.opk ./
          cd ../../
          echo "Pack OlivaDiceOdyssey Done"
          cd ./OlivaStoryCore/OlivaStoryCore
          zip -r ../../../unpack/OlivaStoryCore.opk ./
          cd ../../
          echo "Pack OlivaStoryCore Done"
          cd ./OlivaDiceNativeGUI/OlivaDiceNativeGUI
          zip -r ../../../unpack/OlivaDiceNativeGUI.opk ./
          cd ../../
          cd ../
          echo "Pack OlivaDiceNativeGUI Done"
          cp ./unpack/*.opk ./release/OlivOS/plugin/app
          cp ./unpack/*.opk ./release/OlivOS-Linux/plugin/app
          echo "Setup OlivaDice Done"
          cd ./release/OlivOS/
          zip -r ../../release-final/OlivaDice-OlivOS-Win.zip ./
          cd ../../
          cd ./release/OlivOS-Linux/
          zip -r ../../release-final/OlivaDice-OlivOS-Linux.zip ./
          cd ../../
          cp ./unpack/OlivaDiceCore.opk ./release-final
          echo "Pack OlivaDice Done"
      - name: Artifact OlivaDice-OlivOS-Win
        uses: actions/upload-artifact@v4
        with:
          path: ./release-final/OlivaDice-OlivOS-Win.zip
      - name: Artifact OlivaDice-OlivOS-Linux
        uses: actions/upload-artifact@v4
        with:
          path: ./release-final/OlivaDice-OlivOS-Linux.zip
      - name: Artifact OlivaDiceCore.opk
        uses: actions/upload-artifact@v4
        with:
          path: ./release-final/OlivaDiceCore.opk
      - name: Pack OlivaDice With Version
        if: github.ref_type == 'tag'
        run: |
          cp ./release-final/OlivaDice-OlivOS-Win.zip ./release-final/OlivaDice-${{ github.ref_name }}-OlivOS-Win-${{ env.OlivOSTag }}.zip
          cp ./release-final/OlivaDice-OlivOS-Linux.zip ./release-final/OlivaDice-${{ github.ref_name }}-OlivOS-Linux-${{ env.OlivOSTag }}.zip
      - name: Draft Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          draft: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            ./release-final/*
