name: releaseWithOlivOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download & Unpack OlivOS
        run: |
          mkdir ./download
          mkdir ./unpack
          mkdir ./release
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Win.zip -o ./download/OlivOS-Win.zip
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Win-32.zip -o ./download/OlivOS-Win-32.zip
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Win-32-old.zip -o ./download/OlivOS-Win-32-old.zip
          curl -L https://github.com/OlivOS-Team/OlivOS/releases/latest/download/OlivOS-Linux.zip -o ./download/OlivOS-Linux.zip
          echo "Download OlivOS Done"
          curl -L https://github.com/OlivOS-Team/ChanceCustom/releases/latest/download/ChanceCustom.opk -o ./download/ChanceCustom.opk
          cp ./download/ChanceCustom.opk ./unpack
          echo "Download ChanceCustom Done"
          mkdir ./unpack/OlivOS
          mkdir ./unpack/OlivOS-Win-32
          mkdir ./unpack/OlivOS-Linux
          unzip ./download/OlivOS-Win.zip -d ./unpack/OlivOS
          unzip ./download/OlivOS-Win-32.zip -d ./unpack/OlivOS-Win-32
          unzip ./download/OlivOS-Win-32-old.zip -d ./unpack/OlivOS-Win-32-old
          unzip ./download/OlivOS-Linux.zip -d ./unpack/OlivOS-Linux
          cp -r ./unpack/OlivOS ./release/OlivOS
          cp -r ./unpack/OlivOS-Win-32 ./release/OlivOS-Win-32
          cp -r ./unpack/OlivOS-Win-32-old ./release/OlivOS-Win-32-old
          cp -r ./unpack/OlivOS-Linux ./release/OlivOS-Linux
          mkdir ./release/OlivOS/plugin
          mkdir ./release/OlivOS/plugin/app
          mkdir ./release/OlivOS-Win-32/plugin
          mkdir ./release/OlivOS-Win-32/plugin/app
          mkdir ./release/OlivOS-Win-32-old/plugin
          mkdir ./release/OlivOS-Win-32-old/plugin/app
          mkdir ./release/OlivOS-Linux/plugin
          mkdir ./release/OlivOS-Linux/plugin/app
          echo "Unpack OlivOS Done"
      - name: Checkout OlivaDiceCore
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceCore
          path: ./download/OlivaDiceCore/
      - name: Checkout OlivaDiceJoy
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceJoy
          path: ./download/OlivaDiceJoy/
      - name: Checkout OlivaDiceLogger
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceLogger
          path: ./download/OlivaDiceLogger/
      - name: Checkout OlivaDiceMaster
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceMaster
          path: ./download/OlivaDiceMaster/
      - name: Checkout OlivaDiceOdyssey
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceOdyssey
          path: ./download/OlivaDiceOdyssey/
      - name: Checkout OlivaDiceNativeGUI
        uses: actions/checkout@v3
        with:
          repository: OlivOS-Team/OlivaDiceNativeGUI
          path: ./download/OlivaDiceNativeGUI/
      - name: Pack & Setup OlivaDice
        run: |
          cd ./download/
          cd ./OlivaDiceCore/OlivaDiceCore
          zip -r ../../../unpack/OlivaDiceCore.opk ./
          cd ../../
          echo "Pack OlivaDiceCore Done"
          cd ./OlivaDiceJoy/OlivaDiceJoy
          zip -r ../../../unpack/OlivaDiceJoy.opk ./
          cd ../../
          echo "Pack OlivaDiceJoy Done"
          cd ./OlivaDiceLogger/OlivaDiceLogger
          zip -r ../../../unpack/OlivaDiceLogger.opk ./
          cd ../../
          echo "Pack OlivaDiceLogger Done"
          cd ./OlivaDiceMaster/OlivaDiceMaster
          zip -r ../../../unpack/OlivaDiceMaster.opk ./
          cd ../../
          echo "Pack OlivaDiceMaster Done"
          cd ./OlivaDiceOdyssey/OlivaDiceOdyssey
          zip -r ../../../unpack/OlivaDiceOdyssey.opk ./
          cd ../../
          echo "Pack OlivaDiceOdyssey Done"
          cd ./OlivaDiceNativeGUI/OlivaDiceNativeGUI
          zip -r ../../../unpack/OlivaDiceNativeGUI.opk ./
          cd ../../
          echo "Pack OlivaDiceNativeGUI Done"
          cd ../
          cp ./unpack/*.opk ./release/OlivOS/plugin/app
          cp ./unpack/*.opk ./release/OlivOS-Win-32/plugin/app
          cp ./unpack/*.opk ./release/OlivOS-Win-32-old/plugin/app
          cp ./unpack/*.opk ./release/OlivOS-Linux/plugin/app
          echo "Setup OlivaDice Done"
      - uses: actions/upload-artifact@v3
        with:
          name: OlivaDice-OlivOS-Win
          path: ./release/OlivOS
      - uses: actions/upload-artifact@v3
        with:
          name: OlivaDice-OlivOS-Win-32
          path: ./release/OlivOS-Win-32
      - uses: actions/upload-artifact@v3
        with:
          name: OlivaDice-OlivOS-Win-32-old
          path: ./release/OlivOS-Win-32-old
      - uses: actions/upload-artifact@v3
        with:
          name: OlivaDice-OlivOS-Linux
          path: ./release/OlivOS-Linux
